# Generated by Django 3.1.6 on 2023-06-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Oсновной артикул', models.CharField(max_length=30)),
                ('Ширина', models.CharField(max_length=10)),
                ('ID ARTMIX', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('Деревянный', 'Деревянный'), ('Алюминий', 'Алюминий'), ('Пластиковый', 'Пластиковый')], default='Деревянный', max_length=20)),
                ('confirm', models.BooleanField()),
                ('img', models.ImageField(default='no_image.jpg', upload_to='')),
            ],
        ),
    ]
