# Generated by Django 3.1.6 on 2023-06-26 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Frame',
        ),
    ]
