# Generated by Django 3.1.6 on 2023-06-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_delete_frame'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articul', models.CharField(max_length=30)),
                ('width', models.CharField(max_length=10)),
                ('idarticul', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('Алюминий', 'Алюминий'), ('Пластиковый', 'Пластиковый'), ('Деревянный', 'Деревянный')], default='Деревянный', max_length=20)),
                ('confirm', models.BooleanField()),
                ('img', models.ImageField(default='no_image.jpg', upload_to='')),
            ],
            options={
                'verbose_name': 'Багет',
                'verbose_name_plural': 'Багеты',
            },
        ),
    ]
